accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("post.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from . import views

app_name = "post"
urlpatterns = [
    path("", views.index, name='index'),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("register/", views.post_register, name="post_register"),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('signup/', views.signup, name='signup'),
    path('search/', views.search_results, name='search_results'),
]

accounts/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=200)
    contents = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="images/",blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    author = models.CharField(max_length=200, null=True)
    content = models.CharField(max_length=200, null=True)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.content

post/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class  PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','contents','image')
        labels ={
            'title' : '제목',
            'contents' : '내용'
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'content']
        labels = {
            'author': '이름',
            'content': '내용'
        }


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254, help_text='<br>Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            'username': 'ID'
        }

accounts/views.py
# accounts/views.py

from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("post:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)

@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("post:index")

post/views.py
from django.shortcuts import get_object_or_404, render
from post.forms import PostForm, CommentForm
from django.shortcuts import redirect
from .forms import SignUpForm
from .models import Post, Comment
from django.contrib.auth.decorators import login_required

def index(request):
    posts = Post.objects.all()
    query = request.GET.get('q')


    if query:
        search_results = Post.objects.filter(title__icontains=query)
    else:
        search_results = None
    return render(request, 'post/index.html', {'posts': posts, 'search_results': search_results})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post:post_detail', pk=pk)
    else:
        form = CommentForm()
    return render(request, 'post/post_detail.html', {'post': post, 'form': form, 'comments': comments})

@login_required
def post_register(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('post:index')
    else:
        form = PostForm()
    return render(request, 'post/post_register.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('post:index')
    else:
        form = PostForm(instance=post)
    return render(request, 'post/post_edit.html', {'form': form})

@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post:index')

@login_required
def comment_delete(request, pk, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == 'POST':
        comment.delete()
    return redirect('post:post_detail', pk=pk)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('post:index')  # 회원가입 후 로그인 페이지로 리다이렉트
    else:
        form = SignUpForm()
    return render(request, 'post/signup.html', {'form': form})


def search_results(request):
    query = request.GET.get('q')
    if query:
        results = Post.objects.filter(title__icontains=query)
    else:
        results = None
    return render(request, 'post/index.html', {'query': query, 'results': results})

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'post_list.html', {'posts': posts})

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <div class="navbar">
        <a href="{% url 'accounts:login'%}">로그인</a>
    </div>

    <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="로그아웃">
    </form>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

</body>
</html>

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}

{% block content %}
    <h1>로그인</h1>

    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">로그인</button>
    </form>

{% endblock content %}

post/templates/post/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SpartaMarket</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
    <link rel="icon" type="image/png" href="\static\post\images\sparta.jpg">

    <style>
        .row {
            --bs-gutter-x: calc(1.5rem - 15%);
            --bs-gutter-y: calc(0 - 15%);
            display: flex;
            flex-wrap: wrap;
            margin-top: calc(-1 * var(--bs-gutter-y));
            margin-right: 2%;
            margin-left: 2%;
        }

        body {
            background-color: rgb(0, 0, 0);
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        .video-background {
            position: fixed;
            overflow: hidden;
            z-index: -1;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        .video-background video {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            opacity: 0.5;
        }

        .container {
            color: white;

        }

        footer {
            color: #dddddd;
            position: fixed;
            bottom: 10px;
            left: 0;
            width: 100%;
            z-index: 1000;
            text-align: center;
        }

        .text-body-secondary {
            margin-bottom: 0%;
        }

        table {
            text-align: center;
            counter-reset: rowNumber;
            border-collapse: collapse;
            width: 70%;
        }

        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        td:first-child::before {
            counter-increment: rowNumber;
            content: counter(rowNumber);
        }

        .rank_table {
            display: flex;
            justify-content: center;
        }

        .row {
            --bs-gutter-x: 15px;
            --bs-gutter-y: 15px;
            display: flex;
            flex-wrap: wrap;
            margin-top: calc(-1* var(--bs-gutter-y));
            margin-right: 2%;
            margin-left: 2%;
            flex-direction: row;
        }

        .col {
            text-decoration-line: none;
        }

        a {
            text-decoration: none;
            color: inherit;
        }

        a:hover {
            color: inherit;
        }

        .text-body-secondary {
            color: #ffffff!important;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'post:index' %}">SpartaMarket</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'post:post_register' %}" class="nav-link active">글작성</a>
                            
                        {% else %}
                        <a href="{% url 'accounts:login' %}" class="nav-link active">로그인하고 글작성하기</a>
                        {% endif %}
                    </li>
                </ul>

                {% if request.user.is_authenticated %}
                <h3>안녕하세요, {{ user }}님</h3>
                <form action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="로그아웃">
                </form>

                {% else %}

                <form class="d-flex" role="search" action="{% url 'post:signup' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-success" type="submit">Sign Up</button>
                </form>

                <form class="d-flex" role="search" action="{% url 'accounts:login' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-success" type="submit">Log in</button>
                </form>
                {% endif %}

            </div>
        </div>
    </nav>

    <div class="container my-5 text-center">
        <h1>사고 팔고</h1>
        <div class="row justify-content-center">
            <div class="col-lg-8 px-0">
                <form action="{% url 'post:search_results' %}" method="get">
                    <input type="text" name="q" class="form-control" placeholder="Search" aria-label="Search">
                </form>
            </div>
        </div>
    </div>


    <div class="container">

        <!-- post_list.html -->
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% if results %}
            {% for post in results %}
            <!-- 검색 결과를 표시하는 부분 -->
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <strong class="card-text">{{post.title}}</strong>
                        <p class="card-text">{{post.contents}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                        href="{% url 'post:post_detail' pk=post.pk %}">View</a></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                        href="{% url 'post:post_edit' pk=post.pk %}">Edit</a></button>
                                <button type="button" class="btn btn-sm btn-outline-danger"><a
                                        href="{% url 'post:post_delete' pk=post.pk %}">Delete</a></button>
                            </div>
                            <small class="text-body-secondary">{{post.create_date}}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            {% for post in posts %}
            <!-- 검색 결과가 없을 때 모든 게시물을 표시하는 부분 -->
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <strong class="card-text">{{post.title}}</strong>
                        <p class="card-text">{{post.contents}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                        href="{% url 'post:post_detail' pk=post.pk %}">View</a></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                        href="{% url 'post:post_edit' pk=post.pk %}">Edit</a></button>
                                <button type="button" class="btn btn-sm btn-outline-danger"><a
                                        href="{% url 'post:post_delete' pk=post.pk %}">Delete</a></button>
                            </div>
                            <small class="text-body-secondary">{{post.create_date}}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>

        <br>
        <br>

        <footer class="py-3 my-4 justify-center">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">지효상</a></li>
            </ul>
            <p class="text-center text-body-secondary">2024 SpartaMarket</p>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>

</body>

</html>

post/templates/post/post_detail.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SpartaMarket</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
    <link rel="icon" type="image/png" href="\static\post\images\sparta.jpg">

    <style>
        .row {
            --bs-gutter-x: calc(1.5rem - 15%);
            --bs-gutter-y: calc(0 - 15%);
            display: flex;
            flex-wrap: wrap;
            margin-top: calc(-1 * var(--bs-gutter-y));
            margin-right: 2%;
            margin-left: 2%;
        }

        body {
            background-color: rgb(0, 0, 0);
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        #video-background {
            position: relative;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 100%;
            height: 100%;
            object-fit: cover;
            z-index: -1;
        }

        .video-background {
            position: fixed;
            overflow: hidden;
            z-index: -1;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        .video-background video {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            opacity: 0.5;
        }

        .container {
            color: white;
        }

        footer {
            position: fixed;
            bottom: 10px;
            left: 0;
            width: 100%;
            z-index: 1000;
            text-align: center;
        }

        .text-body-secondary {
            color: white !important;
            margin-bottom: 0%;
        }

        .carousel-control-prev,
        .carousel-control-next {
            margin-right: -190px;
            margin-left: -190px;
        }

        table {
            text-align: center;
            counter-reset: rowNumber;
            border-collapse: collapse;
            width: 70%;
        }

        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        td:first-child::before {
            counter-increment: rowNumber;
            content: counter(rowNumber);
        }

        .rank_table {
            display: flex;
            justify-content: center;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'post:index' %}">SpartaMarket</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li></li>
                </ul>
                <form class="d-flex" role="search" action="{% url 'post:signup' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-success" type="submit">Sign Up</button>
                </form>
            </div>
        </div>
    </nav>

    <br>
    <br>
    <div class="container">
        <!-- post_list.html -->
        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-1 g-1">
            <!-- 검색 결과를 표시하는 부분 -->
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text"><text x="50%" y="50%" fill="#eceeef" dy=".3em">
                                <font size="7em">{{post.title}}</font>
                            </text></p>
                        <p class="card-text">{{post.contents}}</p>
                        
                        {% if post.image %}
                            <img src="{{post.image.url}}">
                        {% endif %}
                        
                        <p class="card-text">작성일자: {{post.create_date}}</p>

                        <br>
                        <p class="card-text"><text x="50%" y="50%" fill="#eceeef" dy=".3em">
                                <font size="5em">댓글</font>
                            </text></p>
                        <div>
                            {% for comment in comments %}

                            {{ comment.author }}: {{ comment.content }}
                            <!-- 댓글 삭제 링크 또는 버튼 -->
                            <form action="{% url 'post:comment_delete' pk=post.pk comment_id=comment.pk %}"
                                method="post">
                                {% csrf_token %}
                                <button type="submit">댓글 삭제</button>
                            </form>
                            <br>
                            {% endfor %}
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">댓글 작성</button>
                            </form>
                        </div>
                        <br><br>
                        <a href="{% url 'post:index' %}">게시판으로 돌아가기</a>


                    </div>
                </div>
            </div>
            <br>

            <footer class="py-3 my-4 justify-center">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">지효상</a></li>
                </ul>
                <p class="text-center text-body-secondary">2024 SpartaMarket</p>
            </footer>

            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
                crossorigin="anonymous"></script>

</body>

</html>

post/templates/post/post_edit.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SpartaMarket</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
    <link rel="icon" type="image/png" href="\static\post\images\sparta.jpg">

    <style>
        .row {
            --bs-gutter-x: calc(1.5rem - 15%);
            --bs-gutter-y: calc(0 - 15%);
            display: flex;
            flex-wrap: wrap;
            margin-top: calc(-1 * var(--bs-gutter-y));
            margin-right: 2%;
            margin-left: 2%;
        }

        body {
            background-color: rgb(0, 0, 0);
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        #video-background {
            position: relative;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 100%;
            height: 100%;
            object-fit: cover;
            z-index: -1;
        }

        .video-background {
            position: fixed;
            overflow: hidden;
            z-index: -1;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        .video-background video {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            opacity: 0.5;
        }

        .container {
            color: white;

        }

        footer {
            position: fixed;
            bottom: 10px;
            left: 0;
            width: 100%;
            z-index: 1000;
            text-align: center;
        }

        .text-body-secondary {
            color: white !important;
            margin-bottom: 0%;
        }

        .carousel-control-prev,
        .carousel-control-next {
            margin-right: -190px;
            margin-left: -190px;
        }

        table {
            text-align: center;
            counter-reset: rowNumber;
            border-collapse: collapse;
            width: 70%;
        }

        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        td:first-child::before {
            counter-increment: rowNumber;
            content: counter(rowNumber);
        }

        .rank_table {
            display: flex;
            justify-content: center;
        }

        .box {
            display: flex;
            flex-direction: column;
            text-align: center;
            justify-content: center;
            align-items: center;
            border: 1px solid #ccc;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            width: 51%;
            margin: 0 auto;
            color: black;
            background-color: white;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'post:index' %}">SpartaMarket</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li></li>
                </ul>
                <form class="d-flex" role="search" action="{% url 'post:signup' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-success" type="submit">Sign Up</button>
                </form>
            </div>
        </div>
    </nav>



    <div class="box">
        <h1>게시글 수정</h1>
        <br>
        <form method="post" class="form-control" enctype="multipart/form-data">
            <br>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">수정 완료</button>
        </form>
    </div>


    <br>


    <footer class="py-3 my-4 justify-center">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">지효상</a></li>
        </ul>
        <p class="text-center text-body-secondary">2024 SpartaMarket</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

</body>

</html>